apiVersion: batch/v1
kind: Job
metadata:
  name: movies-job
  labels:
    app.kubernetes.io/instance: movies
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: job
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: movies-frontend
        app.kubernetes.io/instance: movies
        app.kubernetes.io/component: job
    spec:
      restartPolicy: OnFailure
      containers:
        - name: movies
          image: okteto/movies-api
          command:
            - yarn
            - load
          imagePullPolicy: Always
          env:
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: movies-mongodb
                  key: mongodb-password
            - name: MONGODB_USERNAME
              value: okteto
            - name: MONGODB_DATABASE
              value: okteto
            - name: MONGODB_HOST
              value: movies-mongodb
          resources:
            {}