on: 
  pull_request:
    branches:
      - master

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: Login
      uses: okteto/actions/login@00e3ef35e8ed47cb54f79347eb09a15432cb33ab
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: Create namespace
      uses: okteto/actions/create-namespace@00e3ef35e8ed47cb54f79347eb09a15432cb33ab
      with:
        namespace: pr-${{ github.event.number }}-rberrelleza

    - name: Deploy Application
      uses: okteto/actions/apply@00e3ef35e8ed47cb54f79347eb09a15432cb33ab
      with:
        namespace: pr-${{ github.event.number }}-rberrelleza
        manifest: manifests

    - name: Wait / Sleep
      uses: jakejarvis/wait-action@v0.1.0
      with:
        time: '30s'

    - name: Push API Changes
      uses: okteto/actions/push@00e3ef35e8ed47cb54f79347eb09a15432cb33ab
      with:
        working-directory: api

    - name: Push Frontend Changes
      uses: okteto/actions/push@00e3ef35e8ed47cb54f79347eb09a15432cb33ab
      with:
        working-directory: frontend

    - name: comment PR
      uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: "Preview environment available at https://movies-pr-${{ github.event.number }}-rberrelleza.cloud.okteto.net"
